var Constants = {
	BALL_WIDTH : 219,
	BALL_HEIGHT : 220,
	BALL_JUMP_DISTANCE : 100,
	BALL_JUMP_STEP : 30,
	BALL_JUMP_SECONDS : 0.25,
	BALL_FALL_DISTANCE : 5,
	BALL_FALL_SECONDS : 0.3,
	GAP_WIDTH : 85,
	GAP_HEIGHT : 85,
	
	PHYSICS_DEBUG_NODE_SHOW : true
}